spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/awsmarket
    username: sa
    password:
    driver-class-name: org.h2.Driver
  session:
    store-type: jdbc
    jdbc.initialize-schema: always

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: MySQL5InnoDBDialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100

  profiles:
    include: oauth

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace